problems/java/1/Solution1.java

- [ч] В файле с решением правильно указан package
Тут #2

Solve problem 1 using Java

---

problems/python/1/Solution1.py

Solve problem 1 using Python

---

problems/kotlin/217/Solution2.kt

- Оценка сложности по времени: O(n^2)
- Оценка сложности по времени: O(n)

Solutions kotlin 217

---

problems/java/268/Solution1.java
problems/java/268/Solution2.java

- Оценка сложности по времени: O(n*m)
- Оценка сложности по времени: O(max(n,m))

Solutions java 268

---

problems/python/448/Solution1.py
problems/python/448/Solution2.py

- Оценка сложности по времени: O(n) + O(n) => O(2*n) => O(n)
- Оценка сложности по времени: O(n) * O(1) => O(n)

Solutions 448 python

---

problems/kotlin/20/Solution1.kt

- Оценка сложности по времени: O(n) * O(1) => O(n)

Solve problem 20 using Kotlin

---

problems/kotlin/141/Solution1.kt
problems/kotlin/141/Solution2.kt

- Оценка сложности по времени: O(n) * O(1) => O(n)
- Оценка сложности по времени: O(n)

Solutions kotlin 141

---

problems/kotlin/202/Solution1.kt

- Объяснение концепции: ссылка на YouTube
- Оценка сложности по времени: O(log(n))
- Оценка сложности по памяти: O(log(n))

Solve problem 202 using Kotlin

---

problems/kotlin/54/Solution1.kt

- Объяснение концепции: cсылка на YouTube-выпуск (будет)
- Оценка сложности по времени: O(m * n). Все элементы пройдены единожды
- Оценка сложности по памяти. O(m * n), если учитывать ответ, O(1) иначе

Solve problem 54 using Kotlin

---

problems/kotlin/1706/Solution1.kt

- Объяснение концепции: cсылка на YouTube-выпуск (будет)
- Оценка сложности по времени: O(m * n)

Solve problem 1706 using Kotlin

---

problems/kotlin/202/Solution2.kt

- Объяснение концепции: сгенерированные числа представляются в виде цепочки (связанного списка). Задача сводится к поиску цикла в связанном списке. Используется алгоритм Флойда
- Оценка сложности по времени: O(log(n))

Solve problem 202 using Kotlin (2)

---

problems/kotlin/1351/Solution1.kt
problems/kotlin/1351/Solution2.kt

- Объяснение концепции: полный перебор всех элементов таблицы
- Оценка сложности по времени: O(m * n)
- Объяснение концепции: полный перебор всех элементов таблицы c правого нижнего угла (там вероятнее всего есть отрицательные числа)
- Оценка сложности по времени: O(m * n)

Solutions kotlin 1351

---

problems/kotlin/2418/Solution1.kt

- Оценка сложности по времени: O(n) + O(n*log(n)) + O(n) + O(n) ~ O(n * log(n))
- Оценка сложности по памяти: O(n) + O(n) + O(n) + O(n)  ~ O(n)

Solve problem 2418 using Kotlin

---

problems/java/415/Solution1.java

- Объяснение концепции: итерация от конца строк к началу. Нужно учесть, что одна может быть длиннее другой. Остаток сохраняем и используем в последующих итерациях. while (extra > 0) важно для добавления остатка, если он появился в последней операции
- Оценка сложности по времени: O(max(n,m))
- Оценка сложности по памяти: O(max(n,m) + 1)

Solve problem 415 using Java

---

problems/kotlin/101/Solution1.kt

- Объяснение концепции: DFS по левому и правому поддереву. Только порядок вставки в стек симметричный (чтобы делать симметричный обход)
- Оценка сложности по времени: O(n) + O(n) ~ O(n)
- Оценка сложности по памяти: O(n) + O(n) ~ O(n)

Solve problem 101 using Kotlin

---

problems/kotlin/118/Solution1.kt

- Объяснение концепции
- Оценка сложности по времени: O(n^2)
- Оценка сложности по памяти: O(n^2) для возвращения результата

Add solution 118

---

problems/swift/9/Solution1.swift

- Объяснение концепции
- Оценка сложности по времени
- Оценка сложности по памяти

Solve problem 9 using Swift

---

problems/swift/1/Solution1.swift

- Объяснение концепции
- Оценка сложности по времени
- Оценка сложности по памяти

Solve problem 1 using Swift

---

problems/kotlin/26/Solution1.kt

- Объяснение концепции: https://youtu.be/kynEiQF4EBI
- Оценка сложности по времени: O(n)

Solve problem 26 using Kotlin

---

problems/kotlin/925/Solution1.kt
problems/kotlin/925/Solution2.kt

- Объяснение концепции: https://youtu.be/F9L0juxFv0c
- Оценка сложности по времени: O(max(n), max(m))

Solve problem 925 using Kotlin
